### ISSUE TITLE
Release 2017-02 beta release checklist

### ISSUE THREAD

**Issue by michaelvanvliet** [phnmnl/phenomenal-h2020#4]
As suggested by @sneumann and @pcm32, a list with the remaining tasks before the official release announcement.

**General**
- [ ] Finish blog post "Release announcement"
- [ ] Helpdesk / FAQ
- [ ] Cost estimate

**Infra**
- [ ] Security claims in deliverable docs

**Services** (tool/container/workflow)
- [ ] [Move from develop to master to be included in the release](https://github.com/phnmnl/phenomenal-h2020/wiki/Tool-container-release-process). 
- [ ] [Links to documentation of tools/workflows](https://github.com/phnmnl/phenomenal-h2020/wiki/Release-notes-2017-02)

**Portal**
- [x] Deployments to Google, known problem, requires workaround.
- [x] Guide(s) how to deploy VRE to providers
- [ ] Disclaimers
- [ ] SSL?

**Comment by michaelvanvliet** [comment]
Release finished.
